config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views

from orochi.api.api import api

# DJANGO VIEWS
urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("orochi.website.urls", namespace="website")),
    path("users/", include("orochi.users.urls", namespace="users")),
    path("ya/", include("orochi.ya.urls", namespace="ya")),
    path("accounts/", include("allauth.urls")),
    path("upload/", include("django_file_form.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [path("api/", api.urls)]

# DEBUG
if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

orochi/users/urls.py
from django.urls import path

from orochi.users.views import (
    user_plugins_view,
    user_bookmarks_view,
    user_redirect_view,
    user_yara_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<str:username>/plugins/", view=user_plugins_view, name="plugins"),
    path("<str:username>/bookmarks/", view=user_bookmarks_view, name="bookmarks"),
    path("<str:username>/rules/", view=user_yara_view, name="rules"),
]

orochi/website/urls.py
from uuid import UUID

from django.urls import path, register_converter

from orochi.website import views


class MultiindexConverter:
    regex = "[0-9a-f,-]{36,}"

    def valid_uuid(self, uuid):
        try:
            return UUID(uuid).version
        except ValueError:
            return None

    def to_python(self, value):
        return [x.strip() for x in value.split(",") if self.valid_uuid(x) is not None]

    def to_url(self, value):
        return value


class QueryConverter:
    regex = ".*"

    def to_python(self, value):
        return value

    def to_url(self, value):
        return value


register_converter(MultiindexConverter, "idxs")
register_converter(QueryConverter, "query")


app_name = "website"
urlpatterns = [
    path("", views.index, name="home"),
    path(
        "indexes/<idxs:indexes>/plugin/<str:plugin>/query/<query:query>",
        views.bookmarks,
        name="bookmarks",
    ),
    path(
        "indexes/<idxs:indexes>/plugin/<str:plugin>",
        views.bookmarks,
        name="bookmarks",
    ),
    path("info", views.info, name="index_info"),
    path("create", views.create, name="index_create"),
    path("edit", views.edit, name="index_edit"),
    path("restart", views.restart, name="index_restart"),
    path("analysis", views.analysis, name="analysis"),
    path("generate", views.generate, name="generate"),
    path("tree", views.tree, name="tree"),
    path("parameters", views.parameters, name="parameters"),
    path("export", views.export, name="export"),
    # FOLDERS
    path("folder_create", views.folder_create, name="folder_create"),
    # DOWNLOAD FILES
    path("download", views.download, name="download"),
    # EXTERNAL VIEW
    path("json_view/<path:filepath>", views.json_view, name="json_view"),
    path("hex_view/<str:index>", views.hex_view, name="hex_view"),
    path("get_hex/<str:index>", views.get_hex, name="get_hex"),
    path("search_hex/<str:index>", views.search_hex, name="search_hex"),
    path("vt", views.vt, name="vt"),
    path(
        "diff_view/<str:index_a>/<str:index_b>/<str:plugin>",
        views.diff_view,
        name="diff_view",
    ),
    # USER PAGE
    path("edit_bookmark", views.edit_bookmark, name="edit_bookmark"),
    path("add_bookmark", views.add_bookmark, name="add_bookmark"),
    # SYMBOLS
    path("banner_symbols", views.banner_symbols, name="banner_symbols"),
    path("upload_symbols", views.upload_symbols, name="upload_symbols"),
    path("upload_packages", views.upload_packages, name="upload_packages"),
    path("download_isf", views.download_isf, name="download_isf"),
    path("list_symbols", views.list_symbols, name="list_symbols"),
    # INTERNAL
    path("auth-check", views.auth_check, name="auth_check"),
]

orochi/ya/urls.py
from django.urls import path

from orochi.ya import views

app_name = "ya"
urlpatterns = [
    path("upload", views.upload, name="upload"),
    path("detail", views.detail, name="detail"),
]

orochi/users/views.py
from typing import Any

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView

from orochi.website.models import UserPlugin

User = get_user_model()


class UserYaraView(LoginRequiredMixin, DetailView):
    queryset = User.objects.prefetch_related("rules").all()
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/user_rules.html"

    def get_queryset(self) -> QuerySet[Any]:
        mine = self.request.user == User.objects.get(username=self.kwargs["username"])
        qs = super().get_queryset()
        return qs if mine else qs.none()


user_yara_view = UserYaraView.as_view()


class UserPluginView(LoginRequiredMixin, DetailView):
    queryset = User.objects.prefetch_related("plugins__plugin").all()
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/user_plugins.html"

    def post(self, request, *args, **kwargs):
        action = request.POST.get("action")
        plugin_ids = request.POST.getlist("id[]")
        for plugin in plugin_ids:
            up = get_object_or_404(UserPlugin, pk=plugin, user=request.user)
            up.automatic = action == "enable"
            up.save()
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        messages.add_message(
            request,
            messages.SUCCESS if action == "enable" else messages.ERROR,
            f"{len(plugin_ids)} plugins {action}d",
        )
        return self.render_to_response(context)

    def get_queryset(self) -> QuerySet[Any]:
        mine = self.request.user == User.objects.get(username=self.kwargs["username"])
        qs = super().get_queryset()
        return qs if mine else qs.none()


user_plugins_view = UserPluginView.as_view()


class UserBookmarksView(LoginRequiredMixin, DetailView):
    queryset = User.objects.prefetch_related("bookmarks").all()
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/user_bookmarks.html"

    def get_queryset(self) -> QuerySet[Any]:
        mine = self.request.user == User.objects.get(username=self.kwargs["username"])
        qs = super().get_queryset()
        return qs if mine else qs.none()


user_bookmarks_view = UserBookmarksView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        return reverse(
            "users:bookmarks", kwargs={"username": self.request.user.username}
        )


user_redirect_view = UserRedirectView.as_view()

orochi/website/views.py
import json
import mmap
import os
import re
from pathlib import Path

from dask.distributed import Client, fire_and_forget
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.serializers.json import DjangoJSONEncoder
from django.db import transaction
from django.db.models import F, Q
from django.http import Http404, JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.views.decorators.http import require_http_methods
from guardian.shortcuts import get_objects_for_user, get_perms
from pymisp import MISPEvent, MISPObject, PyMISP
from pymisp.tools import FileObject

from orochi.utils.timeliner import clean_bodywork
from orochi.utils.volatility_dask_elk import get_parameters, manage_upload
from orochi.website.defaults import (
    RESULT_STATUS_DISABLED,
    RESULT_STATUS_EMPTY,
    RESULT_STATUS_NOT_STARTED,
    RESULT_STATUS_RUNNING,
    RESULT_STATUS_SUCCESS,
    SERVICE_MISP,
)
from orochi.website.forms import (
    BookmarkForm,
    DumpForm,
    EditBookmarkForm,
    EditDumpForm,
    FolderForm,
    ParametersForm,
    SymbolBannerForm,
    SymbolISFForm,
    SymbolPackageForm,
    SymbolUploadForm,
)
from orochi.website.models import (
    Bookmark,
    Dump,
    Plugin,
    Result,
    Service,
    UserPlugin,
    Value,
)

COLOR_TEMPLATE = """
    <svg class="bd-placeholder-img rounded me-2" width="20" height="20"
         xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice"
         focusable="false" role="img">
        <rect width="100%" height="100%" fill="{}"></rect>
    </svg>
"""

SYSTEM_COLUMNS = [
    "orochi_createdAt",
    "orochi_os",
    "orochi_plugin",
    "down_path",
]

PLUGIN_WITH_CHILDREN = {
    "frameworkinfo.frameworkinfo": "Data",
    "linux.iomem.iomem": "Name",
    "linux.pstree.pstree": "PID",
    "windows.devicetree.devicetree": "Offset",
    "windows.mbrscan.mbrscan": "Potential MBR at Physical Offset",
    "windows.mftscan.mftscan": "Offset",
    "windows.pstree.pstree": "PID",
    "windows.registry.userassist.userassist": "Hive Offset",
}

INDEX_VALUES_LIST = [
    "folder__name",
    "index",
    "name",
    "color",
    "operating_system",
    "author",
    "upload",
    "status",
    "description",
]


##############################
# NGIN AUTH CHECK
##############################
def auth_check(request):
    """
    A view for Nginx's auth_request.

    The @login_required decorator handles everything. If the user is authenticated,
    Django will execute this view and return a 200 OK. If they are not,
    the decorator will redirect to the login page, which for an auth_request
    results in a non-200 status that Nginx can interpret as "unauthorized".
    """
    if request.user.is_authenticated:
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=401)


##############################
# READONLY CHECK
##############################
def is_not_readonly(user):
    """Check if user is readonly"""
    return not user.groups.filter(name="ReadOnly").exists()


##############################
# PLUGIN
##############################
@login_required
@user_passes_test(is_not_readonly)
@require_http_methods(["GET"])
def parameters(request):
    """Get parameters from volatility api, returns form"""
    data = {
        "html_form": render_to_string(
            "website/partial_params.html",
            {
                "form": ParametersForm(
                    dynamic_fields=get_parameters(request.GET.get("selected_plugin"))
                ),
                "plugin_name": request.GET.get("selected_plugin"),
                "pks": ",".join(request.GET.getlist("selected_indexes[]")),
            },
            request=request,
        ),
    }
    return JsonResponse(data)


##############################
# RESULTS
##############################
@login_required
def generate(request):
    """Sliced data request for analysis ajax datatables request"""
    if request.META.get("HTTP_X_REQUESTED_WITH") != "XMLHttpRequest":
        return JsonResponse({"status_code": 405, "error": "Method Not Allowed"})

    # obtain list of columns
    ui_columns = request.GET.getlist("columns[]")

    # sorting
    sort_column = request.GET.get("order[0][column]") or 0
    sort_column = int(sort_column)
    sort_order = request.GET.get("order[0][dir]") or "asc"

    # manage filters on single columns
    filters = request.GET.getlist("filters[]")
    dict_filters = {}
    if filters:
        for filter in filters:
            name, value = filter.split("___")
            dict_filters[name] = value

    draw = request.GET.get("draw")

    if ui_columns == ["Loading"]:
        return JsonResponse(
            {
                "draw": draw,
                "recordsTotal": 1,
                "recordsFiltered": 1,
                "data": [["Please wait"]],
            }
        )
    elif ui_columns == ["Empty"]:
        return JsonResponse(
            {
                "draw": draw,
                "recordsTotal": 1,
                "recordsFiltered": 1,
                "data": [["Empty data"]],
            }
        )

    # GET DATA
    indexes = request.GET.getlist("indexes[]")
    plugin = request.GET.get("plugin")
    start = int(request.GET.get("start"))
    length = int(request.GET.get("length"))
    search = request.GET.get("search[value]")

    # GET PLUGIN INFO
    plugin = get_object_or_404(Plugin, name=plugin)

    # GET DICT OF COLOR AND CHECK PERMISSIONS
    dumps = Dump.objects.filter(index__in=indexes)
    for dump in dumps:
        if dump not in get_objects_for_user(request.user, "website.can_see"):
            return JsonResponse({"status_code": 403, "error": "Unauthorized"})

    # GET ALL RESULTS
    res = (
        Value.objects.select_related("result__plugin", "result__dump")
        .filter(result__plugin__name=plugin, result__dump__index__in=indexes)
        .filter(result__result=RESULT_STATUS_SUCCESS)
        .annotate(
            orochi_plugin=F("result__plugin__name"),
            orochi_index=F("result__dump__index"),
            orochi_name=F("result__dump__name"),
            orochi_os=F("result__dump__operating_system"),
            orochi_color=F("result__dump__color"),
            orochi_createdAt=F("result__updated_at"),
        )
        .values(
            "orochi_plugin",
            "orochi_index",
            "orochi_name",
            "orochi_os",
            "orochi_color",
            "orochi_createdAt",
            "value",
        )
    )

    total = res.count()

    # first filtering main search
    if search:
        res = res.filter(
            Q(value__icontains=search)
            | Q(orochi_plugin__icontains=search)
            | Q(orochi_name__icontains=search)
            | Q(orochi_os__icontains=search)
            | Q(orochi_createdAt__icontains=search)
        )

    # second filtering on each column (dump/plugin)
    if filters:
        for k, v in dict_filters.items():
            if k.startswith("orochi_"):
                res = res.filter(**{f"{k}__icontains": v})

    try:
        _ = Service.objects.get(name=SERVICE_MISP)
        misp_configured = True
    except Service.DoesNotExist:
        misp_configured = False

    data = []

    # EXPLODE RES
    for item in res:
        tmp = {k: item[k] for k in item.keys() - {"value"}}
        tmp["orochi_color"] = COLOR_TEMPLATE.format(tmp["orochi_color"])

        # third filtering on each column (volatility result)
        filtered = False
        for k, v in item["value"].items():
            if k_filter := dict_filters.get(k):
                if v and k_filter in str(v):
                    tmp[k] = v
                else:
                    filtered = True
            else:
                tmp[k] = v

        if filtered:
            continue

        if item["value"].get("down_path"):
            tmp["actions"] = render_to_string(
                "website/file_download.html",
                {
                    "down_path": item["value"]["down_path"],
                    "misp_configured": misp_configured,
                    "regipy": Path(
                        f"{item['value']['down_path']}.regipy.json"
                    ).exists(),
                    "vt": (
                        Path(f"{item['value']['down_path']}.vt.json").read_text()
                        if Path(f"{item['value']['down_path']}.vt.json").exists()
                        else None
                    ),
                },
            )

        list_row = []
        for column in ui_columns:
            if column in tmp:
                list_row.append(tmp[column])
            else:
                list_row.append("-")

        data.append(list_row)

    filtered = len(data)

    data = sorted(data, key=lambda d: d[sort_column], reverse=sort_order == "asc")

    data = data[start : start + length]

    return JsonResponse(
        {
            "draw": draw,
            "recordsTotal": total,
            "recordsFiltered": filtered,
            "data": data,
        }
    )


def change_keys(obj, title):
    """Change keys for tree rendering"""
    if isinstance(obj, dict):
        new = {}
        for k, v in obj.items():
            if k in SYSTEM_COLUMNS:
                continue
            elif k == "__children":
                if v != []:
                    new["children"] = change_keys(v, title)
                else:
                    continue
            elif k == title:
                new["title"] = v
            else:
                new[k] = v or "-"
    elif isinstance(obj, list):
        new = [change_keys(v, title) for v in obj]
    else:
        return obj
    return new


@login_required
def analysis(request):

orochi/templates/website/hex_view.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{{block.super}}
<link rel="stylesheet" type="text/css" href="{% static 'css/datatables/select.dataTables.min.css' %}" />
{% endblock css %}

{% block fullpage %}
<div class="container py-5">
    <h1>{{name}} [{{index}}]</h1>
    <table class="table table-striped" id="example" style="width:100%">
        <thead>
            <tr>
                <td>Address</td>
                <td>Hex</td>
                <td>Ascii</td>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td>Address</td>
                <td>Hex</td>
                <td>Ascii</td>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock fullpage %}

{% block javascript %}
{{block.super}}
<script type="text/javascript" src="{% static 'js/datatables/dataTables.select.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var last = 0;
        var table = $("#example").DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": "{% url 'website:get_hex' index %}",
            "bSort": false,
            "lengthMenu": [25, 50, 100, 250, 500],
            'columnDefs': [
                {
                    'searchable': false,
                    'targets': [0, 1, 2]
                },
            ],
            "sDom": 'l<"goto"><"next">tip',
        });

        // GOTO -> CONVERT HEX ADDRESS TO PAGE AND GO TO PAGE
        $("div.goto").html(`
            <label>GoTo: <input type="text" class="form-control form-control-sm" id="input_goto">
                <button id="btn_goto" class="btn btn-sm btn-primary">go</button>
            </label>
        `);
        $(document).on('click', '#btn_goto', function () {
            var page = Math.floor(parseInt($("#input_goto").val(), 16) / (table.page.len() * 16));
            table.page(page).draw('page');
        });

        // NEXT -> SEARCH NEXT OCCURRENCE ASYNC AND GO TO PAGE
        $("div.next").html(`
            <label>Search: <input type="text" class="form-control form-control-sm" id="input_next">
                <button id="btn_next" class="btn btn-sm btn-primary">next</button>
                <button id="btn_clear" class="btn btn-sm btn-primary">clear</button>
                <span class="d-none text-danger" id="notfound"> not found!</span>
            </label>
        `);
        $(document).on('click', '#btn_next', function () {
            $("#notfound").addClass('d-none');
            $.ajax({
                url: "{% url 'website:search_hex' index %}",
                type: "get",
                data: { 'last': last, 'findstr': $("#input_next").val() },
                dataType: 'json',
                beforeSend: function () {
                    $("#btn_next").prop("disabled", true);
                    $("#btn_clear").prop("disabled", true);
                },
                success: function (data) {
                    $("#btn_next").prop("disabled", false);
                    $("#btn_clear").prop("disabled", false);
                    if (data.found == 1) {
                        last = data.pos;
                        var page = Math.floor(last / (table.page.len() * 16));
                        table.page(page).draw('page');
                    } else {
                        last = 0;
                        $("#notfound").removeClass('d-none');
                    }
                },
                error: function (error) {
                    $("#btn_next").prop("disabled", true);
                    $("#btn_clear").prop("disabled", true);
                    console.log(error);
                },
            });
        });
        $(document).on('click', '#btn_clear', function () {
            $("#input_next").val('');
            $("#input_goto").val('');
            last = 0;
            table.page(0).draw('page');
        });
    });
</script>
{% endblock javascript %}

orochi/templates/website/list_symbols.html
{% extends "base.html" %}
{% load static %}

{% block modal %}
<div class="modal fade" id="modal-update" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
{% endblock %}

{% block fullpage %}
<div class="container py-5">
  {% include "messages.html" %}
  <div class="tab-content">
    <div class="tab-pane fade show active" id="manage_panel" role="tabpanel" aria-labelledby="manage_panel">
      <div class="card">
        <div class="card-header">
          Manage Symbols
          <button type="button" class="btn btn-sm btn-primary" id="upload-symbols">
            <i class="fa fa-upload"></i> Symbols
          </button>
          <button type="button" class="btn btn-sm btn-secondary" id="upload-packages">
            <i class="fa fa-upload"></i> .deb .ddeb .rmp .exe
          </button>
          <button type="button" class="btn btn-sm btn-success" id="download-isf">
            <i class="fa fa-download"></i> from ISF Server
          </button>
        </div>
        <div class="card-body">
          <table class="table table-striped" id="symbols_list" style="width:100%">
            <thead>
              <tr>
                <th>key</th>
                <th>path</th>
                <th>
                  actions
                  {% csrf_token %}
                </th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock fullpage %}


{% block javascript %}
{{block.super}}
<script src="{% static 'file_form/file_form.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function () {

    var table = $("#symbols_list").DataTable({
      "processing": true,
      "serverSide": true,
      "ajax": {
        "url": "{% url 'api:list_symbols' %}",
        data: function (d) {
          delete d.columns;
          if (d.order.length > 0) {
            order = d.order[0];
            delete d.order;
            d.order_column = order.column;
            d.order_dir = order.dir;
          } else {
            delete d.order;
          }

          if (d.search && d.search.value) {
            search = d.search.value;
            delete d.search;
            d.search = search;
          } else {
            delete d.search;
          }
          return d;
        }
      },
      'columns': [
        { 'data': 'id' },
        { 'data': 'path' },
        {
          sortable: false,
          render: function (data, type, row, meta) {
            if (row.action[0] == 'down') {
              return `<a class='btn btn-sm btn-outline-warning' href='${row.action[1]}'><i class='fas fa-download'></i></a>`
            } else if (row.action[0] == 'delete') {
              return `<a class='btn btn-sm btn-outline-danger symbol-delete' data-path='${row.action[1]}' href='#'><i class='fas fa-trash'></i></a>`
            }
            return ''
          }
        }
      ],
      'order': [[1, 'asc']]
    });

    // DOWNLOAD FROM ISF FORM
    $(document).on('click', '#download-isf', function () {
      $.ajax({
        url: "{% url 'website:download_isf' %}",
        method: 'get',
        dataType: 'json',
        beforeSend: function () {
          $("#modal-update .modal-dialog").removeClass('modal-xl');
          $("#modal-update .modal-content").html('');
          $("#modal-update").modal("show");
        },
        success: function (data) {
          $("#modal-update .modal-content").html(data.html_form);
        }
      });
    });

    // UPLOAD PACKAGE FORM
    $(document).on('click', '#upload-packages', function () {
      $.ajax({
        url: "{% url 'website:upload_packages' %}",
        method: 'get',
        dataType: 'json',
        beforeSend: function () {
          $("#modal-update .modal-dialog").removeClass('modal-xl');
          $("#modal-update .modal-content").html('');
          $("#modal-update").modal("show");
        },
        success: function (data) {
          $("#modal-update .modal-content").html(data.html_form);
          $("#btn_package_add").addClass('disabled');
          $("#btn_symbol_add").addClass('disabled');
          $("#create_loading").hide();
          initUploadFields(
            document.getElementById("packages-upload-index"),
            {
              callbacks: {
                onSuccess: upload => {
                  $("#btn_package_add").removeClass('disabled');
                }
              }
            }
          );
        }
      });
    });

    // UPLOAD SYMBOLS FORM
    $(document).on('click', '#upload-symbols', function () {
      $.ajax({
        url: "{% url 'website:upload_symbols' %}",
        method: 'get',
        dataType: 'json',
        beforeSend: function () {
          $("#modal-update .modal-dialog").removeClass('modal-xl');
          $("#modal-update .modal-content").html('');
          $("#modal-update").modal("show");
        },
        success: function (data) {
          $("#modal-update .modal-content").html(data.html_form);
          $("#btn_symbol_add").addClass('disabled')
          initUploadFields(
            document.getElementById("symbols-upload-index"),
            {
              callbacks: {
                onSuccess: upload => {
                  $("#btn_symbol_add").removeClass('disabled');
                }
              }
            }
          );
        }
      });
    });

    // UPLOAD SYMBOLS FORM SUBMIT
    $(document).on("submit", "#symbols-upload-index", function (e) {
      e.preventDefault();
      var form = $(this);
      var formData = new FormData(this);
      let jsonData = form.serializeArray();
      let obj = { 'info': [] };
      jsonData.forEach(item => {
        if (['csrfmiddlewaretoken', 'symbols-uploads', 'upload_url', 'form_id', 'symbols-metadata'].indexOf(item.name) == -1) {
          obj[item.name] = item.value;
        } else if (item.name == 'symbols-uploads') {
          obj['info'].push({
            'local_folder': '/media/tmp/' + JSON.parse(item.value)[0]['id'],
            'original_name': JSON.parse(item.value)[0]['name'],
          });
        }
      });
      formData.append("payload", JSON.stringify(obj));
      $.ajaxSetup({
        headers: { 'X-CSRFToken': $('input[name="csrfmiddlewaretoken"]').val() }
      });
      $.ajax({
        url: form.attr("action"),
        data: formData,
        type: form.attr("method"),
        processData: false,
        contentType: false,
        dataType: 'json',
        success: function (data) {
          $("#modal-update").modal('hide');
          table.ajax.reload();
          toast({
            title: 'Symbols added!',
            content: 'Symbols added.',
            type: 'success'
          });
        },
        error: function () {
          toast({
            title: 'Error!',
            content: 'Error during symbols upload.',
            type: 'error'
          });
        },
      });
    });

    $(document).on("submit", "#isf-download-index, #packages-upload-index", function (e) {
      e.preventDefault();
      $("#btn_isf_download").html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>');
      $("#btn_isf_download").addClass('disabled');
      var form = $(this);
      var formData = new FormData(this);
      let jsonData = form.serializeArray();
      let obj = { 'info': [] };
      jsonData.forEach(item => {
        if (['csrfmiddlewaretoken', 'packages-uploads', 'upload_url', 'form_id', 'packages-metadata'].indexOf(item.name) == -1) {
          obj[item.name] = item.value;
        } else if (item.name == 'packages-uploads') {
          obj['info'].push({
            'local_folder': '/media/tmp/' + JSON.parse(item.value)[0]['id'],
            'original_name': JSON.parse(item.value)[0]['name'],
          });
        }
      });
      formData.append("payload", JSON.stringify(obj));
      $.ajaxSetup({
        headers: { 'X-CSRFToken': $('input[name="csrfmiddlewaretoken"]').val() }
      });

      $("#create_loading").show();
      $("#btn_package_add").addClass('disabled');
      $("#btn_symbol_add").addClass('disabled');
      $.ajax({
        url: form.attr("action"),
        data: formData,
        contentType: "application/json",
        type: form.attr("method"),
        processData: false,
        contentType: false,
        dataType: 'json',
        success: function (data) {
          $("#modal-update").modal('hide');
          table.ajax.reload();
          toast({
            title: 'Symbols added!',
            content: data.message,
            type: 'success'
          });
        },
        error: function (data) {
          $("#modal-update").modal('hide');
          toast({
            title: 'Error!',
            content: data.responseJSON.errors,
            type: 'error'
          });
        },
      });
    });

    // DELETE SYMBOL
    $(document).on("click", ".symbol-delete", function () {
      var btn = $(this);
      var path = btn.data("path");

      $.ajaxSetup({
        headers: { 'X-CSRFToken': $('input[name="csrfmiddlewaretoken"]').val() }
      });

      $.ajax({
        url: "{% url 'api:delete_symbol' %}?path=" + encodeURIComponent(path),
        method: 'delete',
        dataType: 'json',
        success: function (data) {
          table.ajax.reload();
          toast({
            title: 'Symbols deleted!',
            content: data.message,
            type: 'success'
          });
        },
        error: function (data) {
          toast({
            title: 'Error!',
            content: data.responseJSON.errors,
            type: 'error'
          });
        },
      });
    });

  });
</script>
{% endblock javascript %}